version: "3.9"

services: 
    mlflow:
        build: mlflow
        command: mlflow server  --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}--default-artifact-root s3://mlflow_bucket/mlflow/ --host 0.0.0.0
        expose:
            - "5000"
        ports:
            - "5000:5000"
    db:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        expose:
            - "3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
volumes:
    db_data:
        